sonar.projectKey=cloudguard-frontend
sonar.projectName=CloudGuard Frontend
sonar.projectVersion=1.0

# Vertel Sonar waar de code staat
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts

# Optioneel: als je unit tests en coverage hebt
# sonar.tests=src
# sonar.test.inclusions=**/*.spec.ts
# sonar.javascript.lcov.reportPaths=coverage/cloudguard/lcov.info
