services:
  mysql:
    image: mysql:8.3
    container_name: cloudguard-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloudguard
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  backend:
    build: ./api
    container_name: cloudguard-backend
    restart: unless-stopped
    env_file:
      - ./api/.env
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cloudguard
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # We zeggen hier: "Als het domein klopt, EN de URL begint met /api, stuur het naar de backend"
      - "traefik.http.routers.backend.rule=Host(`cloudguard.cloudmen.net`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=le"
      # Pas deze poort aan als je Spring Boot applicatie op een andere poort draait (standaard is vaak 8080)
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

  frontend:
    build: ./frontend
    container_name: cloudguard-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.frontend.rule=Host(`cloudguard.cloudmen.net`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=80" # Interne Angular/Nginx poort

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge
  traefik:
    external: true
