version: "3.9"

services:
  mysql:
    image: mysql:8.3
    container_name: cloudguard-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloudguard
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  backend:
    build: ./api
    container_name: cloudguard-backend
    volumes:
      - ./api/.env:/app/.env
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cloudguard
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      # Vang alle requests af die op de 'backend' poort (8081) binnenkomen
      - "traefik.http.routers.backend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.backend.entrypoints=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=8080" # Interne Spring Boot poort

  frontend:
    build: ./frontend
    container_name: cloudguard-frontend
    depends_on:
      - backend
    environment:
      # VUL HIER HET IP IN VAN JE VM
      - BACKEND_URL=http://<JOUW_VM_IP_ADRES>:8081
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      # Vang alle requests af die op de 'web' poort (80) binnenkomen
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80" # Interne Angular/Nginx poort

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge
  traefik:
    external: true
