package com.cloudmen.cloudguard.domain.model;

public enum UserRole {
    UNASSIGNED,
    SUPER_ADMIN,

    DASHBOARD_ADMIN,
    USERS_GROUPS_ADMIN,
    ORG_UNITS_ADMIN,
    SHARED_DRIVES_ADMIN,
    DEVICES_ADMIN,
    APP_ACCESS_ADMIN,
    APP_PASSWORDS_ADMIN,
    PASSWORD_SETTINGS_ADMIN,
    DOMAIN_DNS_ADMIN,
    LICENSES_ADMIN,
    NOTIFICATIONS_FEEDBACK_ADMIN,
    SECURITY_PREFERENCES_ADMIN
}
