package com.cloudmen.cloudguard.domain.model;

public enum UserRole {
    UNASSIGNED,
    SUPER_ADMIN,

    USERS_GROUPS_VIEWER,
    ORG_UNITS_VIEWER,
    SHARED_DRIVES_VIEWER,
    DEVICES_VIEWER,
    APP_ACCESS_VIEWER,
    APP_PASSWORDS_VIEWER,
    PASSWORD_SETTINGS_VIEWER,
    DOMAIN_DNS_VIEWER,
    LICENSES_VIEWER,
    NOTIFICATIONS_FEEDBACK_VIEWER,
    SECURITY_PREFERENCES_VIEWER
}
